# Generated by Django 2.2.5 on 2019-10-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
