# Generated by Django 2.2.5 on 2019-10-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inz', '0003_auto_20191018_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='last name'),
        ),
    ]
